name: TurtleSMP
version: '${version}'
main: me.yoursole.turtlesmp.TurtleSMP
api-version: 1.19
authors: [ Yoursole ]
commands:
  life:
    usage: /<command> add/remove playername
  revive:
    usage: /<command> playername